// Package posestoarm implements a generic service that moves an arm
// through the poses generated by an image-to-poses camera.
package posestoarm

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"github.com/golang/geo/r3"

	"go.viam.com/rdk/components/camera"
	"go.viam.com/rdk/logging"
	"go.viam.com/rdk/referenceframe"
	"go.viam.com/rdk/resource"
	"go.viam.com/rdk/services/generic"
	"go.viam.com/rdk/services/motion"
	"go.viam.com/rdk/spatialmath"
)

// Model is the full model triplet for this service.
var Model = resource.NewModel("esha", "portrait-drawing", "poses-to-arm")

func init() {
	resource.RegisterService(generic.API, Model, resource.Registration[resource.Resource, *Config]{
		Constructor: newPosesToArm,
	})
}

// Config describes the attributes for the pose executor.
type Config struct {
	// Camera is the name of the image-to-poses camera that supplies the
	// poses. Required.
	Camera string `json:"camera"`
	// Arm is the name of the arm to move through the poses, using the motion
	// service. Required.
	Arm string `json:"arm"`
}

// Validate ensures the config is valid; camera and arm are required.
func (c *Config) Validate(path string) ([]string, []string, error) {
	if c.Camera == "" {
		return nil, nil, resource.NewConfigValidationFieldRequiredError(path, "camera")
	}
	if c.Arm == "" {
		return nil, nil, resource.NewConfigValidationFieldRequiredError(path, "arm")
	}
	return []string{c.Camera, c.Arm, motion.Named("builtin").String()}, nil, nil
}

type posesToArm struct {
	resource.Named
	resource.AlwaysRebuild

	logger  logging.Logger
	cam     camera.Camera
	armName string
	motion  motion.Service

	// mu guards drawCancel, which is non-nil while a draw is in progress and
	// cancels it.
	mu         sync.Mutex
	drawCancel context.CancelFunc
}

func newPosesToArm(
	ctx context.Context,
	deps resource.Dependencies,
	conf resource.Config,
	logger logging.Logger,
) (resource.Resource, error) {
	cfg, err := resource.NativeConfig[*Config](conf)
	if err != nil {
		return nil, err
	}
	cam, err := camera.FromDependencies(deps, cfg.Camera)
	if err != nil {
		return nil, err
	}
	motionSvc, err := motion.FromDependencies(deps, "builtin")
	if err != nil {
		return nil, err
	}
	return &posesToArm{
		Named:   conf.ResourceName().AsNamed(),
		logger:  logger,
		cam:     cam,
		armName: cfg.Arm,
		motion:  motionSvc,
	}, nil
}

// DoCommand handles arbitrary commands. Supported commands:
//
//	{"command": "draw"} - fetches the poses from the image-to-poses camera's
//	get_poses command and moves the configured arm through them, using the
//	motion service. Only one draw may run at a time.
//	{"command": "stop"} - cancels the in-progress draw, if any.
func (s *posesToArm) DoCommand(ctx context.Context, cmd map[string]interface{}) (map[string]interface{}, error) {
	command, ok := cmd["command"].(string)
	if !ok {
		return nil, fmt.Errorf(`expected a "command" string in the command map, got: %v`, cmd)
	}

	switch command {
	case "draw":
		poses, err := s.fetchPoses(ctx)
		if err != nil {
			return nil, err
		}

		s.mu.Lock()
		if s.drawCancel != nil {
			s.mu.Unlock()
			return nil, errors.New(`a draw is already in progress; send the "stop" command to cancel it`)
		}
		drawCtx, cancel := context.WithCancel(ctx)
		s.drawCancel = cancel
		s.mu.Unlock()
		defer func() {
			s.mu.Lock()
			s.drawCancel = nil
			s.mu.Unlock()
			cancel()
		}()

		for i, pose := range poses {
			if drawCtx.Err() != nil {
				s.logger.Infof("draw stopped after %d of %d poses", i, len(poses))
				return map[string]interface{}{
					"status":    "stopped",
					"completed": i,
					"total":     len(poses),
				}, nil
			}
			if _, err := s.motion.Move(drawCtx, motion.MoveReq{
				ComponentName: s.armName,
				Destination:   referenceframe.NewPoseInFrame(referenceframe.World, pose),
			}); err != nil {
				if drawCtx.Err() != nil {
					s.logger.Infof("draw stopped after %d of %d poses", i, len(poses))
					return map[string]interface{}{
						"status":    "stopped",
						"completed": i,
						"total":     len(poses),
					}, nil
				}
				return nil, fmt.Errorf("failed to move to pose %d of %d: %w", i+1, len(poses), err)
			}
			if (i+1)%100 == 0 {
				s.logger.Infof("drew %d of %d poses", i+1, len(poses))
			}
		}

		return map[string]interface{}{
			"status":    "drawing complete",
			"completed": len(poses),
			"total":     len(poses),
		}, nil
	case "stop":
		s.mu.Lock()
		cancel := s.drawCancel
		s.mu.Unlock()
		if cancel == nil {
			return map[string]interface{}{"status": "no draw in progress"}, nil
		}
		cancel()
		return map[string]interface{}{"status": "stop requested"}, nil
	default:
		return nil, fmt.Errorf("unknown command: %q", command)
	}
}

// Close cancels any in-progress draw.
func (s *posesToArm) Close(ctx context.Context) error {
	s.mu.Lock()
	cancel := s.drawCancel
	s.mu.Unlock()
	if cancel != nil {
		cancel()
	}
	return nil
}

// fetchPoses gets the poses from the camera's get_poses command.
func (s *posesToArm) fetchPoses(ctx context.Context) ([]spatialmath.Pose, error) {
	resp, err := s.cam.DoCommand(ctx, map[string]interface{}{"command": "get_poses"})
	if err != nil {
		return nil, fmt.Errorf("camera get_poses command failed: %w", err)
	}
	rawPoses, ok := resp["poses"].([]interface{})
	if !ok {
		return nil, fmt.Errorf(`camera get_poses response has no "poses" list: %v`, resp)
	}
	if len(rawPoses) == 0 {
		return nil, errors.New("camera generated no poses")
	}

	poses := make([]spatialmath.Pose, len(rawPoses))
	for i, raw := range rawPoses {
		p, ok := raw.(map[string]interface{})
		if !ok {
			return nil, fmt.Errorf("unexpected pose format at index %d: %v", i, raw)
		}
		poses[i] = spatialmath.NewPose(
			r3.Vector{X: asFloat(p["x"]), Y: asFloat(p["y"]), Z: asFloat(p["z"])},
			&spatialmath.OrientationVectorDegrees{
				OX:    asFloat(p["o_x"]),
				OY:    asFloat(p["o_y"]),
				OZ:    asFloat(p["o_z"]),
				Theta: asFloat(p["theta"]),
			},
		)
	}
	return poses, nil
}

func asFloat(v interface{}) float64 {
	f, _ := v.(float64)
	return f
}
