// Package posestoarm implements a generic service that moves an arm
// through the poses generated by an image-to-poses camera.
package posestoarm

import (
	"bytes"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"image/png"
	"sync"
	"time"

	"github.com/golang/geo/r3"

	"go.viam.com/rdk/components/camera"
	"go.viam.com/rdk/logging"
	"go.viam.com/rdk/motionplan"
	"go.viam.com/rdk/referenceframe"
	"go.viam.com/rdk/resource"
	"go.viam.com/rdk/services/generic"
	"go.viam.com/rdk/services/motion"
	"go.viam.com/rdk/spatialmath"

	"portrait-drawing/paperimage"
)

// Tolerances for linear-constrained moves: how far the arm may deviate from
// the straight-line path and orientation while crossing at hover height.
const (
	linearLineToleranceMM          = 2.0
	linearOrientationToleranceDegs = 5.0
)

// maxDwellSeconds is how long the pen pauses on a fully dark (darkness 1.0)
// dot to let ink bleed in; dwell scales linearly with the dot's darkness.
const maxDwellSeconds = 2

// drawPose is one pose in the drawing sequence; linear marks poses that
// should be reached on a straight-line-constrained path.
type drawPose struct {
	pose   spatialmath.Pose
	linear bool
	// Level of darkness, where 0 is not dark and 1 is full darkness
	darkness float64
	// preview is the dot's position in the camera's upright preview frame
	// (mm from the drawing area's top-left); nil for hover/travel poses.
	preview *[2]float64
}

// drawing is what the current or last draw is drawing, for progress images:
// the paper as the preview shows it and each contact pose's dot, in order.
type drawing struct {
	paper paperimage.Paper
	// dots[i] is the dot for pose index poseIndex[i].
	dots      []paperimage.Dot
	poseIndex []int
	// cache of the last rendered image and the completed count it showed.
	pngFor int
	png    []byte
}

// Model is the full model triplet for this service.
var Model = resource.NewModel("chess-piece-detection", "portrait-drawing", "poses-to-arm")

func init() {
	resource.RegisterService(generic.API, Model, resource.Registration[resource.Resource, *Config]{
		Constructor: newPosesToArm,
	})
}

// Config describes the attributes for the pose executor.
type Config struct {
	// Camera is the name of the image-to-poses camera that supplies the
	// poses. Required.
	Camera string `json:"camera"`
	// Arm is the name of the arm to move through the poses, using the motion
	// service. Required.
	Arm string `json:"arm"`
}

// Validate ensures the config is valid; camera and arm are required.
func (c *Config) Validate(path string) ([]string, []string, error) {
	if c.Camera == "" {
		return nil, nil, resource.NewConfigValidationFieldRequiredError(path, "camera")
	}
	if c.Arm == "" {
		return nil, nil, resource.NewConfigValidationFieldRequiredError(path, "arm")
	}
	return []string{c.Camera, c.Arm, motion.Named("builtin").String()}, nil, nil
}

// Draw states reported by the status command.
const (
	stateIdle         = "idle"
	stateFetching     = "fetching"
	stateDrawing      = "drawing"
	stateShowingPaper = "showing_paper"
	stateStopped      = "stopped"
	stateComplete     = "complete"
	stateError        = "error"

	// showPaperMinHoverMM keeps the pen off the paper while showing corners
	// even when hover_above_mm is 0.
	showPaperMinHoverMM = 5.0
)

type posesToArm struct {
	resource.Named
	resource.AlwaysRebuild

	logger  logging.Logger
	cam     camera.Camera
	armName string
	motion  motion.Service

	// mu guards the fields below. drawCancel is non-nil while a draw is in
	// progress and cancels it; the rest describe the current or last draw.
	mu         sync.Mutex
	drawCancel context.CancelFunc
	drawWG     sync.WaitGroup
	drawState  string
	completed  int
	total      int
	lastErr    string
	// drawing describes the current or last draw's dots; nil if none.
	drawing *drawing
}

func newPosesToArm(
	ctx context.Context,
	deps resource.Dependencies,
	conf resource.Config,
	logger logging.Logger,
) (resource.Resource, error) {
	cfg, err := resource.NativeConfig[*Config](conf)
	if err != nil {
		return nil, err
	}
	cam, err := camera.FromProvider(deps, cfg.Camera)
	if err != nil {
		return nil, err
	}
	motionSvc, err := motion.FromProvider(deps, "builtin")
	if err != nil {
		return nil, err
	}
	return &posesToArm{
		Named:     conf.ResourceName().AsNamed(),
		logger:    logger,
		cam:       cam,
		armName:   cfg.Arm,
		motion:    motionSvc,
		drawState: stateIdle,
	}, nil
}

// DoCommand handles arbitrary commands. Supported commands:
//
//	{"command": "draw"} - fetches the poses from the image-to-poses camera's
//	get_poses command and moves the configured arm through them, using the
//	motion service. Optional "threshold" and "point_spacing_mm" are forwarded
//	to get_poses as overrides. The draw runs in the background and this
//	command returns immediately with {"status": "started"}; poll "status" for
//	progress. Only one draw may run at a time.
//	{"command": "show_paper"} - asks the camera where the paper is (its
//	get_paper command) and dips the pen to hover height above each corner in
//	turn, so the sheet can be placed under it. Runs in the background like
//	draw and shares its single-flight guard; "stop" cancels it.
//	{"command": "stop"} - cancels the in-progress draw or show_paper, if any.
//	{"command": "drawing_image"} - returns a picture of what the current or
//	last draw is drawing: its dots on the paper, completed ones black and the
//	rest gray, as "png_base64" (empty string if there is none) with
//	"mime_type" and the "completed" count it shows.
//	{"command": "status"} - returns the state of the current or last action:
//	"state" (idle, fetching, drawing, showing_paper, stopped, complete, or
//	error), "completed" and "total" counts (poses for a draw, corners for
//	show_paper), and "error" (empty unless state is error).
func (s *posesToArm) DoCommand(ctx context.Context, cmd map[string]any) (map[string]any, error) {
	command, ok := cmd["command"].(string)
	if !ok {
		return nil, fmt.Errorf(`expected a "command" string in the command map, got: %v`, cmd)
	}

	switch command {
	case "draw":
		// Forward the get_poses overrides, if given.
		posesCmd := map[string]any{"command": "get_poses", "include_preview": true}
		for _, key := range []string{"threshold", "point_spacing_mm"} {
			if v, ok := cmd[key]; ok {
				posesCmd[key] = v
			}
		}
		if err := s.startAction(stateFetching, func(ctx context.Context) { s.runDraw(ctx, posesCmd) }); err != nil {
			return nil, err
		}
		return map[string]any{"status": "started"}, nil
	case "show_paper":
		if err := s.startAction(stateShowingPaper, s.runShowPaper); err != nil {
			return nil, err
		}
		return map[string]any{"status": "started"}, nil
	case "stop":
		s.mu.Lock()
		cancel := s.drawCancel
		s.mu.Unlock()
		if cancel == nil {
			return map[string]any{"status": "no draw in progress"}, nil
		}
		cancel()
		// Wait (without holding mu, which the draw goroutine needs to exit)
		// so the arm has actually stopped when this returns.
		s.drawWG.Wait()
		return map[string]any{"status": "stopped"}, nil
	case "drawing_image":
		png, completed, err := s.drawingImage()
		if err != nil {
			return nil, err
		}
		return map[string]any{
			"png_base64": base64.StdEncoding.EncodeToString(png),
			"mime_type":  "image/png",
			"completed":  completed,
		}, nil
	case "status":
		s.mu.Lock()
		defer s.mu.Unlock()
		return map[string]any{
			"state":     s.drawState,
			"completed": s.completed,
			"total":     s.total,
			"error":     s.lastErr,
		}, nil
	default:
		return nil, fmt.Errorf("unknown command: %q", command)
	}
}

// startAction begins a background action (a draw or show_paper) if none is
// running: it resets the reported state to initial, detaches the action from
// the request context so it outlives the request, and runs it in a goroutine
// that clears the in-progress marker when it returns.
func (s *posesToArm) startAction(initial string, run func(ctx context.Context)) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.drawCancel != nil {
		return errors.New(`a draw is already in progress; send the "stop" command to cancel it`)
	}
	ctx, cancel := context.WithCancel(context.Background())
	s.drawCancel = cancel
	s.drawState = initial
	s.completed = 0
	s.total = 0
	s.lastErr = ""
	if initial == stateFetching {
		s.drawing = nil
	}
	s.drawWG.Add(1)
	go func() {
		defer func() {
			s.mu.Lock()
			s.drawCancel = nil
			s.mu.Unlock()
			cancel()
			s.drawWG.Done()
		}()
		run(ctx)
	}()
	return nil
}

// finish records the terminal state of a background action.
func (s *posesToArm) finish(state string, completed, total int, err error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.drawState = state
	s.completed = completed
	s.total = total
	if err != nil {
		s.lastErr = err.Error()
		s.logger.Errorw("action failed", "state", state, "error", err)
	}
}

// runDraw fetches the poses and moves the arm through them, recording
// progress in the service's state until it finishes, fails, or is cancelled.
func (s *posesToArm) runDraw(ctx context.Context, posesCmd map[string]any) {
	finish := s.finish

	poses, dr, err := s.fetchPoses(ctx, posesCmd)
	if err != nil {
		if ctx.Err() != nil {
			finish(stateStopped, 0, 0, nil)
			return
		}
		finish(stateError, 0, 0, err)
		return
	}

	s.mu.Lock()
	s.drawState = stateDrawing
	s.total = len(poses)
	s.drawing = dr
	s.mu.Unlock()

	for i, pose := range poses {
		if ctx.Err() != nil {
			s.logger.Infof("draw stopped after %d of %d poses", i, len(poses))
			finish(stateStopped, i, len(poses), nil)
			return
		}
		req := motion.MoveReq{
			ComponentName: s.armName,
			Destination:   referenceframe.NewPoseInFrame(referenceframe.World, pose.pose),
		}
		if pose.linear {
			req.Constraints = &motionplan.Constraints{
				LinearConstraint: []motionplan.LinearConstraint{{
					LineToleranceMm:          linearLineToleranceMM,
					OrientationToleranceDegs: linearOrientationToleranceDegs,
				}},
			}
		}
		if _, err := s.motion.Move(ctx, req); err != nil {
			if ctx.Err() != nil {
				s.logger.Infof("draw stopped after %d of %d poses", i, len(poses))
				finish(stateStopped, i, len(poses), nil)
				return
			}
			finish(stateError, i, len(poses), fmt.Errorf("failed to move to pose %d of %d: %w", i+1, len(poses), err))
			return
		}
		s.mu.Lock()
		s.completed = i + 1
		s.mu.Unlock()
		if (i+1)%100 == 0 {
			s.logger.Infof("drew %d of %d poses", i+1, len(poses))
		}
		// Dwell on the dot: holding the pen still lets ink bleed into the
		// paper, so darker dots get a longer pause.
		dwell := time.Duration(pose.darkness * maxDwellSeconds * float64(time.Second))
		time.Sleep(dwell)
	}

	s.logger.Infof("drawing complete: %d poses", len(poses))
	finish(stateComplete, len(poses), len(poses), nil)
}

// runShowPaper asks the camera where the paper is and dips the pen to hover
// height above each corner in turn, so a sheet can be placed under it.
func (s *posesToArm) runShowPaper(ctx context.Context) {
	resp, err := s.cam.DoCommand(ctx, map[string]any{"command": "get_paper"})
	if err != nil {
		s.finish(stateError, 0, 0, fmt.Errorf("camera get_paper command failed: %w", err))
		return
	}
	rawCorners, ok := resp["corners"].([]any)
	if !ok || len(rawCorners) == 0 {
		s.finish(stateError, 0, 0, fmt.Errorf(`camera get_paper response has no "corners" list: %v`, resp))
		return
	}
	z := asFloat(resp["surface_z_mm"])
	hover := asFloat(resp["hover_above_mm"])
	if hover < showPaperMinHoverMM {
		hover = showPaperMinHoverMM
	}

	s.mu.Lock()
	s.total = len(rawCorners)
	s.mu.Unlock()

	downward := &spatialmath.OrientationVectorDegrees{OX: 0, OY: 0, OZ: -1, Theta: 0}
	move := func(x, y, zz float64) error {
		_, err := s.motion.Move(ctx, motion.MoveReq{
			ComponentName: s.armName,
			Destination:   referenceframe.NewPoseInFrame(referenceframe.World, spatialmath.NewPose(r3.Vector{X: x, Y: y, Z: zz}, downward)),
		})
		return err
	}
	for i, raw := range rawCorners {
		c, ok := raw.([]any)
		if !ok || len(c) != 2 {
			s.finish(stateError, i, len(rawCorners), fmt.Errorf("unexpected corner format at index %d: %v", i, raw))
			return
		}
		x, y := asFloat(c[0]), asFloat(c[1])
		// Approach from high above, dip to hover height, lift.
		steps := []float64{z + 10*hover, z + hover}
		for _, zz := range steps {
			if err := move(x, y, zz); err != nil {
				if ctx.Err() != nil {
					s.finish(stateStopped, i, len(rawCorners), nil)
					return
				}
				s.finish(stateError, i, len(rawCorners), fmt.Errorf("failed to move to paper corner %d of %d: %w", i+1, len(rawCorners), err))
				return
			}
		}
		if err := move(x, y, z+10*hover); err != nil && ctx.Err() == nil {
			s.finish(stateError, i, len(rawCorners), fmt.Errorf("failed to lift from paper corner %d: %w", i+1, err))
			return
		}
		s.mu.Lock()
		s.completed = i + 1
		s.mu.Unlock()
	}
	s.logger.Infof("showed %d paper corners", len(rawCorners))
	s.finish(stateComplete, len(rawCorners), len(rawCorners), nil)
}

// drawingImage renders the current or last draw's dots with the completed
// ones black, caching the image per completed count. It returns nil bytes
// when there is no drawing.
func (s *posesToArm) drawingImage() ([]byte, int, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	dr := s.drawing
	if dr == nil {
		return nil, 0, nil
	}
	completed := s.completed
	if dr.pngFor == completed && dr.png != nil {
		return dr.png, completed, nil
	}
	for i := range dr.dots {
		dr.dots[i].Done = dr.poseIndex[i] < completed
	}
	var buf bytes.Buffer
	if err := png.Encode(&buf, paperimage.Render(dr.paper, dr.dots)); err != nil {
		return nil, 0, fmt.Errorf("failed to encode the drawing image: %w", err)
	}
	dr.pngFor, dr.png = completed, buf.Bytes()
	return dr.png, completed, nil
}

// fetchPoses gets the poses from the camera by sending it posesCmd, a
// get_poses command with any overrides, along with the preview PNG rendered
// from the same frame when the response carries one (nil otherwise).
func (s *posesToArm) fetchPoses(ctx context.Context, posesCmd map[string]any) ([]drawPose, *drawing, error) {
	resp, err := s.cam.DoCommand(ctx, posesCmd)
	if err != nil {
		return nil, nil, fmt.Errorf("camera get_poses command failed: %w", err)
	}
	rawPoses, ok := resp["poses"].([]any)
	if !ok {
		return nil, nil, fmt.Errorf(`camera get_poses response has no "poses" list: %v`, resp)
	}
	if len(rawPoses) == 0 {
		return nil, nil, errors.New("camera generated no poses")
	}
	var dr *drawing
	if pv, ok := resp["preview"].(map[string]any); ok {
		dr = &drawing{
			paper: paperimage.Paper{
				WidthMM:   asFloat(pv["paper_width_mm"]),
				HeightMM:  asFloat(pv["paper_height_mm"]),
				MarginMM:  asFloat(pv["margin_mm"]),
				SpacingMM: asFloat(resp["point_spacing_mm"]),
			},
			pngFor: -1,
		}
	}

	poses := make([]drawPose, len(rawPoses))
	for i, raw := range rawPoses {
		p, ok := raw.(map[string]any)
		if !ok {
			return nil, nil, fmt.Errorf("unexpected pose format at index %d: %v", i, raw)
		}
		linear, _ := p["linear"].(bool)
		darkness, _ := p["darkness"].(float64)
		poses[i] = drawPose{
			pose: spatialmath.NewPose(
				r3.Vector{X: asFloat(p["x"]), Y: asFloat(p["y"]), Z: asFloat(p["z"])},
				&spatialmath.OrientationVectorDegrees{
					OX:    asFloat(p["o_x"]),
					OY:    asFloat(p["o_y"]),
					OZ:    asFloat(p["o_z"]),
					Theta: asFloat(p["theta"]),
				},
			),
			linear:   linear,
			darkness: darkness,
		}
		if u, ok := p["u"].(float64); ok {
			if v, ok := p["v"].(float64); ok {
				poses[i].preview = &[2]float64{u, v}
				if dr != nil {
					dr.dots = append(dr.dots, paperimage.Dot{U: u, V: v})
					dr.poseIndex = append(dr.poseIndex, i)
				}
			}
		}
	}
	return poses, dr, nil
}

func asFloat(v any) float64 {
	f, _ := v.(float64)
	return f
}

// Close cancels any in-progress draw and waits for it to finish.
func (s *posesToArm) Close(ctx context.Context) error {
	s.mu.Lock()
	cancel := s.drawCancel
	s.mu.Unlock()
	if cancel != nil {
		cancel()
	}
	s.drawWG.Wait()
	return nil
}
