// Package posestoarm implements a generic service that moves an arm
// through the poses generated by an image-to-poses camera.
package posestoarm

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"github.com/golang/geo/r3"

	"go.viam.com/rdk/components/camera"
	"go.viam.com/rdk/logging"
	"go.viam.com/rdk/motionplan"
	"go.viam.com/rdk/referenceframe"
	"go.viam.com/rdk/resource"
	"go.viam.com/rdk/services/generic"
	"go.viam.com/rdk/services/motion"
	"go.viam.com/rdk/spatialmath"
)

// Tolerances for linear-constrained moves: how far the arm may deviate from
// the straight-line path and orientation while crossing at hover height.
const (
	linearLineToleranceMM          = 2.0
	linearOrientationToleranceDegs = 5.0
)

// drawPose is one pose in the drawing sequence; linear marks poses that
// should be reached on a straight-line-constrained path.
type drawPose struct {
	pose   spatialmath.Pose
	linear bool
}

// Model is the full model triplet for this service.
var Model = resource.NewModel("chess-piece-detection", "portrait-drawing", "poses-to-arm")

func init() {
	resource.RegisterService(generic.API, Model, resource.Registration[resource.Resource, *Config]{
		Constructor: newPosesToArm,
	})
}

// Config describes the attributes for the pose executor.
type Config struct {
	// Camera is the name of the image-to-poses camera that supplies the
	// poses. Required.
	Camera string `json:"camera"`
	// Arm is the name of the arm to move through the poses, using the motion
	// service. Required.
	Arm string `json:"arm"`
}

// Validate ensures the config is valid; camera and arm are required.
func (c *Config) Validate(path string) ([]string, []string, error) {
	if c.Camera == "" {
		return nil, nil, resource.NewConfigValidationFieldRequiredError(path, "camera")
	}
	if c.Arm == "" {
		return nil, nil, resource.NewConfigValidationFieldRequiredError(path, "arm")
	}
	return []string{c.Camera, c.Arm, motion.Named("builtin").String()}, nil, nil
}

// Draw states reported by the status command.
const (
	stateIdle     = "idle"
	stateFetching = "fetching"
	stateDrawing  = "drawing"
	stateStopped  = "stopped"
	stateComplete = "complete"
	stateError    = "error"
)

type posesToArm struct {
	resource.Named
	resource.AlwaysRebuild

	logger  logging.Logger
	cam     camera.Camera
	armName string
	motion  motion.Service

	// mu guards the fields below. drawCancel is non-nil while a draw is in
	// progress and cancels it; the rest describe the current or last draw.
	mu         sync.Mutex
	drawCancel context.CancelFunc
	drawWG     sync.WaitGroup
	drawState  string
	completed  int
	total      int
	lastErr    string
}

func newPosesToArm(
	ctx context.Context,
	deps resource.Dependencies,
	conf resource.Config,
	logger logging.Logger,
) (resource.Resource, error) {
	cfg, err := resource.NativeConfig[*Config](conf)
	if err != nil {
		return nil, err
	}
	cam, err := camera.FromDependencies(deps, cfg.Camera)
	if err != nil {
		return nil, err
	}
	motionSvc, err := motion.FromDependencies(deps, "builtin")
	if err != nil {
		return nil, err
	}
	return &posesToArm{
		Named:     conf.ResourceName().AsNamed(),
		logger:    logger,
		cam:       cam,
		armName:   cfg.Arm,
		motion:    motionSvc,
		drawState: stateIdle,
	}, nil
}

// DoCommand handles arbitrary commands. Supported commands:
//
//	{"command": "draw"} - fetches the poses from the image-to-poses camera's
//	get_poses command and moves the configured arm through them, using the
//	motion service. Optional "threshold" and "point_spacing_mm" are forwarded
//	to get_poses as overrides. The draw runs in the background and this
//	command returns immediately with {"status": "started"}; poll "status" for
//	progress. Only one draw may run at a time.
//	{"command": "stop"} - cancels the in-progress draw, if any.
//	{"command": "status"} - returns the state of the current or last draw:
//	"state" (idle, fetching, drawing, stopped, complete, or error),
//	"completed" and "total" pose counts, and "error" (empty unless state is
//	error).
func (s *posesToArm) DoCommand(ctx context.Context, cmd map[string]interface{}) (map[string]interface{}, error) {
	command, ok := cmd["command"].(string)
	if !ok {
		return nil, fmt.Errorf(`expected a "command" string in the command map, got: %v`, cmd)
	}

	switch command {
	case "draw":
		s.mu.Lock()
		if s.drawCancel != nil {
			s.mu.Unlock()
			return nil, errors.New(`a draw is already in progress; send the "stop" command to cancel it`)
		}
		// The draw outlives this request, so it must not inherit ctx.
		drawCtx, cancel := context.WithCancel(context.Background())
		s.drawCancel = cancel
		s.drawState = stateFetching
		s.completed = 0
		s.total = 0
		s.lastErr = ""
		s.mu.Unlock()

		// Forward the get_poses overrides, if given.
		posesCmd := map[string]interface{}{"command": "get_poses"}
		for _, key := range []string{"threshold", "point_spacing_mm"} {
			if v, ok := cmd[key]; ok {
				posesCmd[key] = v
			}
		}

		s.drawWG.Add(1)
		go s.runDraw(drawCtx, cancel, posesCmd)
		return map[string]interface{}{"status": "started"}, nil
	case "stop":
		s.mu.Lock()
		cancel := s.drawCancel
		s.mu.Unlock()
		if cancel == nil {
			return map[string]interface{}{"status": "no draw in progress"}, nil
		}
		cancel()
		// Wait (without holding mu, which the draw goroutine needs to exit)
		// so the arm has actually stopped when this returns.
		s.drawWG.Wait()
		return map[string]interface{}{"status": "stopped"}, nil
	case "status":
		s.mu.Lock()
		defer s.mu.Unlock()
		return map[string]interface{}{
			"state":     s.drawState,
			"completed": s.completed,
			"total":     s.total,
			"error":     s.lastErr,
		}, nil
	default:
		return nil, fmt.Errorf("unknown command: %q", command)
	}
}

// runDraw fetches the poses and moves the arm through them, recording
// progress in the service's state until it finishes, fails, or is cancelled.
func (s *posesToArm) runDraw(ctx context.Context, cancel context.CancelFunc, posesCmd map[string]interface{}) {
	defer func() {
		s.mu.Lock()
		s.drawCancel = nil
		s.mu.Unlock()
		cancel()
		s.drawWG.Done()
	}()

	finish := func(state string, completed, total int, err error) {
		s.mu.Lock()
		defer s.mu.Unlock()
		s.drawState = state
		s.completed = completed
		s.total = total
		if err != nil {
			s.lastErr = err.Error()
			s.logger.Errorw("draw failed", "error", err)
		}
	}

	poses, err := s.fetchPoses(ctx, posesCmd)
	if err != nil {
		if ctx.Err() != nil {
			finish(stateStopped, 0, 0, nil)
			return
		}
		finish(stateError, 0, 0, err)
		return
	}

	s.mu.Lock()
	s.drawState = stateDrawing
	s.total = len(poses)
	s.mu.Unlock()

	for i, pose := range poses {
		if ctx.Err() != nil {
			s.logger.Infof("draw stopped after %d of %d poses", i, len(poses))
			finish(stateStopped, i, len(poses), nil)
			return
		}
		req := motion.MoveReq{
			ComponentName: s.armName,
			Destination:   referenceframe.NewPoseInFrame(referenceframe.World, pose.pose),
		}
		if pose.linear {
			req.Constraints = &motionplan.Constraints{
				LinearConstraint: []motionplan.LinearConstraint{{
					LineToleranceMm:          linearLineToleranceMM,
					OrientationToleranceDegs: linearOrientationToleranceDegs,
				}},
			}
		}
		if _, err := s.motion.Move(ctx, req); err != nil {
			if ctx.Err() != nil {
				s.logger.Infof("draw stopped after %d of %d poses", i, len(poses))
				finish(stateStopped, i, len(poses), nil)
				return
			}
			finish(stateError, i, len(poses), fmt.Errorf("failed to move to pose %d of %d: %w", i+1, len(poses), err))
			return
		}
		s.mu.Lock()
		s.completed = i + 1
		s.mu.Unlock()
		if (i+1)%100 == 0 {
			s.logger.Infof("drew %d of %d poses", i+1, len(poses))
		}
	}

	s.logger.Infof("drawing complete: %d poses", len(poses))
	finish(stateComplete, len(poses), len(poses), nil)
}

// fetchPoses gets the poses from the camera by sending it posesCmd, a
// get_poses command with any overrides.
func (s *posesToArm) fetchPoses(ctx context.Context, posesCmd map[string]interface{}) ([]drawPose, error) {
	resp, err := s.cam.DoCommand(ctx, posesCmd)
	if err != nil {
		return nil, fmt.Errorf("camera get_poses command failed: %w", err)
	}
	rawPoses, ok := resp["poses"].([]interface{})
	if !ok {
		return nil, fmt.Errorf(`camera get_poses response has no "poses" list: %v`, resp)
	}
	if len(rawPoses) == 0 {
		return nil, errors.New("camera generated no poses")
	}

	poses := make([]drawPose, len(rawPoses))
	for i, raw := range rawPoses {
		p, ok := raw.(map[string]interface{})
		if !ok {
			return nil, fmt.Errorf("unexpected pose format at index %d: %v", i, raw)
		}
		linear, _ := p["linear"].(bool)
		poses[i] = drawPose{
			pose: spatialmath.NewPose(
				r3.Vector{X: asFloat(p["x"]), Y: asFloat(p["y"]), Z: asFloat(p["z"])},
				&spatialmath.OrientationVectorDegrees{
					OX:    asFloat(p["o_x"]),
					OY:    asFloat(p["o_y"]),
					OZ:    asFloat(p["o_z"]),
					Theta: asFloat(p["theta"]),
				},
			),
			linear: linear,
		}
	}
	return poses, nil
}

func asFloat(v interface{}) float64 {
	f, _ := v.(float64)
	return f
}

// Close cancels any in-progress draw and waits for it to finish.
func (s *posesToArm) Close(ctx context.Context) error {
	s.mu.Lock()
	cancel := s.drawCancel
	s.mu.Unlock()
	if cancel != nil {
		cancel()
	}
	s.drawWG.Wait()
	return nil
}
